// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartLocalServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLocalServer'](arg1, arg2, arg3, arg4);
}

export function StartPublicServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPublicServer'](arg1, arg2, arg3, arg4);
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
