// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetLocalIPs():Promise<Array<string>>;

export function SelectFolder():Promise<string>;

export function StartLocalServer(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function StartPublicServer(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function StopServer():Promise<void>;
