// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckUpdate() {
  return window['go']['main']['App']['CheckUpdate']();
}

export function ConnectP2P(arg1) {
  return window['go']['main']['App']['ConnectP2P'](arg1);
}

export function DiscoverP2PPeers(arg1) {
  return window['go']['main']['App']['DiscoverP2PPeers'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetP2PStatus() {
  return window['go']['main']['App']['GetP2PStatus']();
}

export function InstallUpdate(arg1) {
  return window['go']['main']['App']['InstallUpdate'](arg1);
}

export function OpenInExplorer(arg1) {
  return window['go']['main']['App']['OpenInExplorer'](arg1);
}

export function SelectFile() {
  return window['go']['main']['App']['SelectFile']();
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function StartLocalServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLocalServer'](arg1, arg2, arg3, arg4);
}

export function StartP2PSend(arg1) {
  return window['go']['main']['App']['StartP2PSend'](arg1);
}

export function StartProxy(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartProxy'](arg1, arg2, arg3);
}

export function StartPublicServer(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartPublicServer'](arg1, arg2, arg3, arg4);
}

export function StopP2PTransfer() {
  return window['go']['main']['App']['StopP2PTransfer']();
}

export function StopServer() {
  return window['go']['main']['App']['StopServer']();
}
