// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckUpdate():Promise<main.UpdateInfo>;

export function ConnectP2P(arg1:string):Promise<string>;

export function DiscoverP2PPeers(arg1:number):Promise<string>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetP2PStatus():Promise<string>;

export function InstallUpdate(arg1:string):Promise<string>;

export function OpenInExplorer(arg1:string):Promise<void>;

export function SelectFile():Promise<string>;

export function SelectFolder():Promise<string>;

export function StartLocalServer(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function StartP2PSend(arg1:string):Promise<string>;

export function StartProxy(arg1:string,arg2:string,arg3:string):Promise<string>;

export function StartPublicServer(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function StopP2PTransfer():Promise<void>;

export function StopServer():Promise<void>;
